### ISSUE TITLE
Pull method doesn't work

### ISSUE THREAD

**Issue by OleksandrSankin** [amihaiemil/zold-java-client#35]
```
RestfulZoldWts wts = new RestfulZoldWts("my-zold-key");
Wallet wallet = wts.pull();
```
Got error:

```
Exception in thread "main" javax.json.stream.JsonParsingException: Unexpected char 60 at (line no=1, column no=1, offset=0)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:532)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:415)
	at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:222)
	at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:101)
	at com.amihaiemil.zold.PayloadOf.lambda$new$1(PayloadOf.java:82)
	at com.amihaiemil.zold.JsonResource.<init>(JsonResource.java:53)
	at com.amihaiemil.zold.PayloadOf.<init>(PayloadOf.java:78)
	at com.amihaiemil.zold.MatchStatus.handleResponse(MatchStatus.java:67)
	at com.amihaiemil.zold.MatchStatus.handleResponse(MatchStatus.java:40)
	at com.amihaiemil.zold.WaitForWallet.handleResponse(WaitForWallet.java:82)
	at com.amihaiemil.zold.WaitForWallet.handleResponse(WaitForWallet.java:45)
```

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@oleksandrsankin[/z](https://www.0crat.com/u/oleksandrsankin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/GFCHY7NQG) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @oleksandrsankin[/z](https://www.0crat.com/u/oleksandrsankin)

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#35](https://github.com/amihaiemil/zold-java-client/issues/35) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @oleksandrsankin[/z](https://www.0crat.com/u/oleksandrsankin)

**Comment by 0crat** [comment]
Job `gh:amihaiemil/zold-java-client#35` doesn't exist in WBS, can't create order
